#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

"""sync-zizmor-versions.py: regenerate the hash-pinned requirements file for
every stable release of zizmor on PyPI, plus `support/zizmor-version` (the
version this action runs by default)."""

import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, NoReturn

PACKAGE = "zizmor"
PYPI_JSON = f"https://pypi.org/pypi/{PACKAGE}/json"
STABLE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
RETRIES = 5

HERE = Path(__file__).resolve().parent
LOCKS = HERE / "locks"
VERSION = HERE / "zizmor-version"

CI = os.environ.get("CI") == "true"


def die(message: str) -> NoReturn:
    print(f"::error::{message}" if CI else f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def releases() -> dict[str, list[dict[str, Any]]]:
    """The PyPI release index for `PACKAGE`. PyPI is occasionally flaky, so
    this retries a few times before giving up."""
    for attempt in range(1, RETRIES + 1):
        try:
            with urllib.request.urlopen(PYPI_JSON, timeout=30) as response:
                return json.load(response)["releases"]
        except (OSError, ValueError, KeyError) as exc:
            if attempt == RETRIES:
                die(f"Could not fetch {PYPI_JSON}: {exc}")
            time.sleep(attempt)

    raise AssertionError("unreachable")


def main() -> None:
    LOCKS.mkdir(exist_ok=True)

    written = []
    for version, files in releases().items():
        # Skip prereleases (e.g. 1.30.0rc1) and fully yanked releases.
        if not STABLE.match(version):
            continue
        wheels = [
            f for f in files if f["packagetype"] == "bdist_wheel" and not f["yanked"]
        ]
        if not wheels:
            continue

        # zizmor ships prebuilt wheels and has no runtime dependencies, so a
        # lock is just the set of wheel hashes for one version. If that ever
        # stops being true, `--require-hashes` will fail loudly on the
        # unpinned dependency rather than install it unverified.
        hashes = sorted(f["digests"]["sha256"] for f in wheels)
        body = " \\\n".join(f"    --hash=sha256:{h}" for h in hashes)
        (LOCKS / f"{PACKAGE}-{version}.txt").write_text(
            f"# Generated by support/{Path(__file__).name}; do not edit.\n"
            f"{PACKAGE}=={version} \\\n{body}\n"
        )
        written.append(version)

    if not written:
        die(f"Found no stable release of {PACKAGE!r} on PyPI")

    newest = max(written, key=lambda v: tuple(int(p) for p in v.split(".")))
    VERSION.write_text(f"{newest}\n")
    print(f"Default version: {newest}", file=sys.stderr)


if __name__ == "__main__":
    main()
