#!/usr/bin/env bash

# sync-zizmor-versions.sh: regenerate the hash-pinned requirements file for
# every stable release of zizmor on PyPI, plus `support/zizmor-version`
# (the version this action runs by default).

set -eu

CI=${CI:-false}
PACKAGE="zizmor"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

err() {
    [[ "${CI}" = "true" ]] && echo "::error::${*}" || echo "ERROR: ${*}" >&2
}

die() {
  err "${*}"
  exit 1
}

installed() {
    command -v "${1}" >/dev/null 2>&1
}

installed curl || die "'curl' is required to continue"
installed python3 || die "'python3' is required to continue"

mkdir -p "${HERE}/locks"

# zizmor ships prebuilt wheels and has no runtime dependencies, so a lock is
# just the set of wheel hashes for one version. If that ever stops being
# true, `--require-hashes` will fail loudly on the unpinned dependency rather
# than install it unverified.
curl --fail --silent --show-error --retry 5 \
    "https://pypi.org/pypi/${PACKAGE}/json" \
    | LOCKS_DIR="${HERE}/locks" PACKAGE="${PACKAGE}" python3 -c '
import json
import os
import pathlib
import re
import sys

package = os.environ["PACKAGE"]
locks = pathlib.Path(os.environ["LOCKS_DIR"])
stable = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")

releases = json.load(sys.stdin)["releases"]
written = []

for version, files in releases.items():
    # Skip prereleases (e.g. 1.30.0rc1) and fully yanked releases.
    if not stable.match(version):
        continue
    wheels = [f for f in files if f["packagetype"] == "bdist_wheel" and not f["yanked"]]
    if not wheels:
        continue

    hashes = sorted(f["digests"]["sha256"] for f in wheels)
    body = " \\\n".join(f"    --hash=sha256:{h}" for h in hashes)
    locks.joinpath(f"{package}-{version}.txt").write_text(
        f"# Generated by support/sync-zizmor-versions.sh; do not edit.\n"
        f"{package}=={version} \\\n{body}\n"
    )
    written.append(version)

if not written:
    sys.exit(f"Found no stable release of {package!r} on PyPI")

newest = max(written, key=lambda v: tuple(int(p) for p in v.split(".")))
print(newest)
' > "${HERE}/zizmor-version"

echo "Default version: $(< "${HERE}/zizmor-version")" >&2
