name: zizmor-action
description: Run zizmor from GitHub Actions 🌈

branding:
  icon: "shield"
  color: "blue"

inputs:
  inputs:
    description: |
      The inputs to pass to `zizmor`.

      This should be a whitespace-separated list of inputs. Inputs will
      be split with shell splitting rules.
    required: false
    default: "."
  online-audits:
    description: |
      Whether to run online audits.
    required: false
    default: "true"
  persona:
    description: |
      The auditing persona to use.

      This can be 'regular' (default), 'pedantic', or 'auditor'.
    required: false
    default: "regular"
  min-severity:
    description: |
      The minimum severity to report findings for.

      This can be 'unknown', 'informational', 'low', 'medium', or 'high'.
    required: false
  min-confidence:
    description: |
      The minimum confidence to report findings for.

      This can be 'unknown', 'low', 'medium', or 'high'.
    required: false
  version:
    description: The version of zizmor to use
    required: false
    default: latest
  token:
    description: |
      The GitHub API token to use for both zizmor and
      GitHub Advanced Security (if the latter is enabled).
    required: false
    default: ${{ github.token }}
  advanced-security:
    description: |
      Whether to enable GitHub Advanced Security for zizmor's results.

      This will use the SARIF output format under the hood and will upload the
      results to the repository's security tab.
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Run zizmor
      id: run-zizmor
      run: |
        "${GITHUB_ACTION_PATH}/action.sh"
      env:
        GHA_ZIZMOR_INPUTS: ${{ inputs.inputs }}
        GHA_ZIZMOR_ONLINE_AUDITS: ${{ inputs.online-audits }}
        GHA_ZIZMOR_PERSONA: ${{ inputs.persona }}
        GHA_ZIZMOR_MIN_SEVERITY: ${{ inputs.min-severity }}
        GHA_ZIZMOR_MIN_CONFIDENCE: ${{ inputs.min-confidence }}
        GHA_ZIZMOR_VERSION: ${{ inputs.version }}
        GHA_ZIZMOR_TOKEN: ${{ inputs.token }}
        GHA_ZIZMOR_ADVANCED_SECURITY: ${{ inputs.advanced-security }}
      shell: bash

    - name: Upload SARIF file to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@fca7ace96b7d713c7035871441bd52efbe39e27e # v3.28.19
      if: ${{ inputs.advanced-security == 'true' }}
      with:
        sarif_file: ${{ steps.run-zizmor.outputs.sarif-file }}
        category: zizmor
